# Docker Compose Configuration
# visit https://docs.docker.com/compose/

version: '3.8'
services:
  # app service for your backend
  app:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DATABASE_NAME: Learning
      DATABASE_USER: root
      DATABASE_PASS: toor
      DATABASE_URI: mongodb://localhost:27017/
    ports:
      - '4000:4000'
    depends_on:
      - database

  # start the mongodb service as container
  database:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'